print(3 + 4)
print(3 - 4)
print(3 * 4)
print(3 / 4)
print(3 ** 4)
print(3 % 4)
print(3 // 4)
print('My name')
print('My family name')
print('France')
print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4 - 4j))
print(type(['Asabeneh','Python', 'Finland']))
print(type('My name'))
print(type('My family name'))
print(type('France'))